In [84]:
import pandas as pd

In [85]:
teams = pd.read_csv("../data/MTeams.csv")
odds = pd.read_csv("../data/sky_data/first_round_odds_ncaam.csv")

In [86]:
odds

      kaggle_team          Date  odds
0     Abilene Chr  Mar 20, 2021   8.5
1     Abilene Chr  Mar 21, 2019  20.5
2       Air Force  Mar 16, 2006   8.0
3       Air Force  Mar 18, 2004   8.5
4           Akron  Mar 17, 2022  13.5
...           ...           ...   ...
1751       Oregon  Mar 21, 2025  -6.5
1752       Auburn  Mar 20, 2025 -32.5
1753  Mississippi  Mar 21, 2025   1.5
1754         Duke  Mar 21, 2025 -32.5
1755     Illinois  Mar 21, 2025  -3.5

[1756 rows x 3 columns]

In [87]:
odds['Season'] = pd.to_datetime(odds["Date"], format='%b %d, %Y').dt.year

In [88]:
odds = odds[odds.Season != 2025].drop("Season", axis =1)

In [89]:
teams[teams.TeamName.str.contains("Miss")].TeamName.unique()

array(['Mississippi', 'Mississippi St', 'Missouri', 'Missouri KC',
       'Missouri St', 'SE Missouri St', 'Southern Miss'], dtype=object)

In [90]:
teams[teams.TeamName == "Illinois"].TeamName.unique()

array(['Illinois'], dtype=object)

In [91]:
to_insert = pd.DataFrame([['Louisville', 'Mar 20, 2025', -2.5],
['Purdue', 'Mar 20, 2025', -8.5],
['Wisconsin', 'Mar 20, 2025', -17.5],
['Houston', 'Mar 20, 2025', -28.5],
['Clemson', 'Mar 20, 2025', -7.5],
['BYU', 'Mar 20, 2025', -2.5],
['Gonzaga', 'Mar 20, 2025', -6.5],
['Tennessee', 'Mar 20, 2025', -18.5],
['Kansas', 'Mar 20, 2025', -5.5],
['Texas A&M', 'Mar 20, 2025', -8.5],
['Missouri', 'Mar 20, 2025', -6.5],
['UCLA', 'Mar 20, 2025', -5.5],
["St John's", 'Mar 20, 2025', -18.5],
['Michigan', 'Mar 20, 2025', -2.5],
['Texas Tech', 'Mar 20, 2025', -14.5],

['Mississippi St', 'Mar 21, 2025', -1.5],
['Alabama', 'Mar 21, 2025', -22.5],
['Iowa St', 'Mar 21, 2025', -14.5],
['Colorado St', 'Mar 21, 2025', -1.5],
["St Mary's CA", 'Mar 21, 2025', -4.5],
["Maryland", 'Mar 21, 2025', -10.5],
["Florida", 'Mar 21, 2025', -28.5],
["Kentucky", 'Mar 21, 2025', -11.5],
["Marquette", 'Mar 21, 2025', -4.5],
["Arizona", 'Mar 21, 2025', -14.5],
["Connecticut", 'Mar 21, 2025', -5.5],
["Michigan St", 'Mar 21, 2025', -17.5],
["Oregon", 'Mar 21, 2025', -6.5],

["Auburn", 'Mar 20, 2025', -32.5],
["Mississippi", 'Mar 21, 2025', 1.5],
["Duke", 'Mar 21, 2025', -32.5],
["Illinois", 'Mar 21, 2025', -2.5],
],

columns = odds.columns

)

In [92]:
odds = pd.concat([odds, to_insert], axis=0)

In [93]:
odds.to_csv('../data/sky_data/first_round_odds_ncaam.csv', index=False)

In [94]:
odds

    kaggle_team          Date  odds
0   Abilene Chr  Mar 20, 2021   8.5
1   Abilene Chr  Mar 21, 2019  20.5
2     Air Force  Mar 16, 2006   8.0
3     Air Force  Mar 18, 2004   8.5
4         Akron  Mar 17, 2022  13.5
..          ...           ...   ...
27       Oregon  Mar 21, 2025  -6.5
28       Auburn  Mar 20, 2025 -32.5
29  Mississippi  Mar 21, 2025   1.5
30         Duke  Mar 21, 2025 -32.5
31     Illinois  Mar 21, 2025  -2.5

[1756 rows x 3 columns]