If I every come back to this notebook...

I was trying to understand why I got different predictions / scores using the same code from last year vs. this year. 

It turns out it's because last year I only had the ordinals through day 114 instead of 133

It's probably worth checking the staleness of these ordinals going forward

In [ ]:
import pandas as pd
import numpy as np
rankings_2025 = pd.read_csv('../data/MMasseyOrdinals.csv')
rankings_2024 = pd.read_csv('../../2024_model/data/MMasseyOrdinals.csv')

In [ ]:
last_day = rankings_2025.groupby('Season').agg({'RankingDayNum':'max'}).rename(
                                    columns = {'RankingDayNum': 'last_day'})


end_rankings = rankings_2025.join(last_day, on = 'Season')
end_rankings = end_rankings[ (end_rankings.RankingDayNum == end_rankings.last_day)
                            & (end_rankings.SystemName =='WLK')]
end_rankings = end_rankings.groupby(['TeamID', 'Season']).agg({'OrdinalRank':np.mean})
end_rankings.reset_index(inplace = True)
end_rankings.columns = ['TeamID', 'Season', 'avg_rank']
end_rankings['final_rank'] = 100-4*np.log(end_rankings['avg_rank']+1)-end_rankings['avg_rank']/22

/var/folders/h5/f91pbgmj0rj6v0ls3y8zc5l40000gn/T/ipykernel_74969/2829857516.py:11: FutureWarning: The provided callable <function mean at 0x1080c8040> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  end_rankings = end_rankings.groupby(['TeamID', 'Season']).agg({'OrdinalRank':np.mean})

In [29]:
last_day = rankings_2024.groupby('Season').agg({'RankingDayNum':'max'}).rename(
                                    columns = {'RankingDayNum': 'last_day'})


end_rankings_2024 = rankings_2024.join(last_day, on = 'Season')
end_rankings_2024 = end_rankings_2024[ (end_rankings_2024.RankingDayNum == end_rankings_2024.last_day)
                            & (end_rankings_2024.SystemName =='WLK')]


end_rankings_2024 = end_rankings_2024.groupby(['TeamID', 'Season']).agg({'OrdinalRank':np.mean})
end_rankings_2024.reset_index(inplace = True)

/var/folders/h5/f91pbgmj0rj6v0ls3y8zc5l40000gn/T/ipykernel_74969/2921324621.py:10: FutureWarning: The provided callable <function mean at 0x1080c8040> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  end_rankings_2024 = end_rankings_2024.groupby(['TeamID', 'Season']).agg({'OrdinalRank':np.mean})

In [28]:
end_rankings_2024

               OrdinalRank
TeamID Season
1101   2014          330.0
       2015          332.0
       2016          304.0
       2017          307.0
       2018          261.0
...                    ...
1476   2023          320.0
       2024          356.0
1477   2023          312.0
       2024          319.0
1478   2024          316.0

[7613 rows x 1 columns]

      TeamID  Season  OrdinalRank
1242    1163    2024          3.0

In [ ]:
end_rankings_2024.columns = ['TeamID', 'Season', 'avg_rank']
end_rankings_2024['final_rank'] = 100-4*np.log(end_rankings_2024['avg_rank']+1)-end_rankings_2024['avg_rank']/22

In [22]:
end_rankings_2024[(end_rankings_2024.Season == 2024)
                  & (end_rankings_2024.TeamID == 1163)]

      TeamID  Season  avg_rank  final_rank
1242    1163    2024         3   94.318459

In [12]:
end_rankings[(end_rankings.Season == 2024)
                  & (end_rankings.TeamID == 1163)]

      TeamID  Season  avg_rank  final_rank
1298    1163    2024       1.0   97.181957

In [16]:
rankings_2024[(rankings_2024.SystemName == "WLK")
              & (rankings_2024.TeamID == 1163)
              & (rankings_2024.Season == 2024)].sort_values(by="RankingDayNum", ascending=False)

         Season  RankingDayNum SystemName  TeamID  OrdinalRank
5204321    2024            114        WLK    1163            3
5185060    2024            107        WLK    1163            2
5165799    2024            100        WLK    1163            3
5146178    2024             93        WLK    1163            3
5126920    2024             86        WLK    1163            5
5108023    2024             79        WLK    1163            7
5070953    2024             65        WLK    1163            9
5052780    2024             58        WLK    1163            7
5034968    2024             51        WLK    1163            7
5018242    2024             44        WLK    1163            5
5001878    2024             37        WLK    1163            7
4985876    2024             30        WLK    1163            9

In [31]:
last_day = rankings_2024.groupby('Season').agg({'RankingDayNum':'max'}).rename(
                                    columns = {'RankingDayNum': 'last_day'})


end_rankings_2024 = rankings_2024.join(last_day, on = 'Season')
end_rankings_2024 = end_rankings_2024[ (end_rankings_2024.RankingDayNum == end_rankings_2024.last_day)
                            & (end_rankings_2024.SystemName =='WLK')]

end_rankings_2024[(end_rankings_2024.Season == 2024) & (end_rankings_2024.TeamID == 1163)
                  ]

         Season  RankingDayNum SystemName  TeamID  OrdinalRank  last_day
5204321    2024            114        WLK    1163            3       114

In [35]:
end_rankings_2024[(end_rankings_2024.Season == 2024) & (end_rankings_2024.TeamID == 1345)
                  ]

         Season  RankingDayNum SystemName  TeamID  OrdinalRank  last_day
5204498    2024            114        WLK    1345            1       114

In [32]:
last_day = rankings_2025.groupby('Season').agg({'RankingDayNum':'max'}).rename(
                                    columns = {'RankingDayNum': 'last_day'})


end_rankings = rankings_2025.join(last_day, on = 'Season')
end_rankings = end_rankings[ (end_rankings.RankingDayNum == end_rankings.last_day)
                            & (end_rankings.SystemName =='WLK')]


end_rankings[(end_rankings.Season == 2024) & (end_rankings.TeamID == 1163)
                  ]

         Season  RankingDayNum SystemName  TeamID  OrdinalRank  last_day
5264251    2024            133        WLK    1163            1       133

In [34]:
end_rankings[(end_rankings.Season == 2024) & (end_rankings.TeamID == 1345)
                  ]

         Season  RankingDayNum SystemName  TeamID  OrdinalRank  last_day
5264428    2024            133        WLK    1345            3       133