### Imports

In [953]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from typing import Any, List, Union
from bs4 import BeautifulSoup
import tqdm
import requests

import Levenshtein
import pandas as pd
from itertools import product
import Levenshtein

### Set Up Data

In [951]:
all_first_round_dates = [
    "20080321", "20080320", 
    "20090320", "20090319", 
    "20100319", "20100318",
    "20110318", "20110317", 
    "20120316", "20120315", 
    "20130322", "20130321",
    "20140321", "20140320", 
    "20150320", "20150319", 
    "20160318", "20160317",
    "20170317", "20170316", 
    "20180316", "20180315", 
    "20190322", "20190321",
    "20200320", "20200319",    
    "20210319", "20210320", 
    "20220318", "20220317",
    "20230317", "20230316", 
    "20240322", "20240321"
]

day_before_tournament_start_dict = {
    '2008': '20080319', '2009': '20090318', '2010': '20100317',
    '2011': '20110316', '2012': '20120320', '2013': '20130319',
    '2014': '20140319', '2015': '20150318', '2016': '20160316',
    '2017': '20170315', '2018': '20180314', '2019': '20190320',
    '2020': '20200318', '2021': '20210317', '2022': '20220316',
    '2023': '20230315', '2024': '20240320'
}

day_before_tournament_start_df = pd.DataFrame(list(day_before_tournament_start_dict.items()), columns=['year', 'day_before_tourney_start'])
day_before_tournament_start_df['season_start_date'] = (day_before_tournament_start_df['year'].astype(int) - 1).astype(str) + '1101'

### Torvik Player Data Scraping

In [812]:
def build_url(year: str, start_date: str, end_date: str) -> str:
    """
    Build the URL for scraping player stats from Bart Torvik's website.

    Args:
        start_date: The start date in 'YYYYMMDD' format.
        end_date: The end date in 'YYYYMMDD' format.

    Returns:
        A formatted URL string.
    """
    base_url = "https://barttorvik.com/playerstat.php"
    params = (
        "link=y",
        "sIndex=53",
        "minmin=5",
        f"year={year}",
        f"start={start_date}",
        f"end={end_date}"
    )
    return f"{base_url}?{'&'.join(params)}"


def click_games_column(driver: webdriver.Chrome) -> None:
    """
    Wait for the "Games" column span to be clickable and click it.

    Args:
        driver: The Selenium webdriver instance.
    """
    try:
        games_element = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//span[@class='sname' and @id='3']"))
        )
        games_element.click()
        print("Clicked on 'Games' column successfully.")
        time.sleep(2)  # Allow time for the table to update.
    except Exception as e:
        print("Error clicking 'Games' column:", e)


def click_show_more(driver: webdriver.Chrome, max_clicks: int = 40) -> None:
    """
    Continuously click the "Show 100 more" button until it is no longer clickable or
    the maximum number of clicks is reached.

    Args:
        driver: The Selenium webdriver instance.
        max_clicks: Maximum number of times to click the button.
    """
    clicks = 0
    while clicks < max_clicks:
        try:
            expand_element = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable((By.ID, "expand"))
            )
            show_more_button = expand_element.find_element(By.TAG_NAME, "a")
            show_more_button.click()
            print(f"'Show 100 more' clicked ({clicks + 1}/{max_clicks})")
            time.sleep(2)  # Wait for new content to load.
            clicks += 1
        except Exception as e:
            print("No more 'Show 100 more' button found or an error occurred:", e)
            break


def get_html_from_torvik_players(year:str, start_date: str, end_date: str, max_page_expansion_clicks:int=40) -> str:
    """
    Scrapes player statistics from Bart Torvik's website for a given date range.
    
    The function loads the page, clicks the "Games" column to add it to the dataset,
    repeatedly clicks "Show 100 more" to load all data, and then returns the full HTML.
    
    Args:
        start_date: The start date in 'YYYYMMDD' format.
        end_date: The end date in 'YYYYMMDD' format.
    
    Returns:
        The HTML source of the fully loaded page.
    """
    url: str = build_url(year, start_date, end_date)
    print(f"Loading URL: {url}")

    # Initialize the webdriver (adjust if using a different browser)
    driver: Any = webdriver.Chrome()
    driver.get(url)

    time.sleep(30)

    # Click on the "Games" column to include it in the data.
    click_games_column(driver)

    # Click the "Show 100 more" button repeatedly to load more data.
    click_show_more(driver, max_clicks=max_page_expansion_clicks)

    # Retrieve the complete HTML once all content is loaded.
    html_source: str = driver.page_source
    driver.quit()

    return html_source

In [813]:
def extract_complete_row(row: List[str]) -> List[str]:
    """
    Extracts only the relevant columns from a row based on predefined indices.

    Args:
        row (List[str]): A list of strings representing a row's data.

    Returns:
        List[str]: The filtered row with selected columns.
    """
    selected_indices = {0, 2, 3, 4, 6, 7, 8, 10, 11, 13, 16, 18, 19, 20, 21, 22, 23, 24, 26, 27, 28}
    return [cell for i, cell in enumerate(row) if i in selected_indices]


def parse_table(html_source: str) -> List[List[str]]:
    """
    Parses the HTML source to extract table data.

    Args:
        html_source (str): The raw HTML content.

    Returns:
        List[List[str]]: A list of rows, where each row is a list of cell values.
    """
    soup = BeautifulSoup(html_source, "html.parser")

    # Locate the table by its style attribute
    table = soup.find("table", {"style": "white-space:nowrap;margin:auto;table-layout:fixed"})
    if not table:
        raise ValueError("Table not found!")

    # Locate the <tbody> if it exists, otherwise get all rows directly from <table>
    tbody = table.find("tbody")
    rows = tbody.find_all("tr") if tbody else table.find_all("tr")

    extracted_data = []
    for row in rows:
        cells = row.find_all(["td", "th"])  # Some rows may use <th> for data
        row_data = [cell.get_text(strip=True) for cell in cells]
        filtered_row = extract_complete_row(row_data)
        if filtered_row:
            extracted_data.append(filtered_row)

    return extracted_data


def get_data_from_html(html_source: str) -> pd.DataFrame:
    """
    Extracts data from an HTML table and returns it as a pandas DataFrame.

    Args:
        html_source (str): The HTML content of the page.

    Returns:
        pd.DataFrame: The extracted table data as a DataFrame.
    """
    data = parse_table(html_source)

    # Define column headers
    headers = [
        "Rk", "Class", "Height", "Player", "Team", "Conf", "Games", "Min%", "PRPG!", "BPM",
        "ORTG", "USG", "EFG", "TS", "OR", "DR", "AST", "TO", "BLK", "STL", "FTR"
    ]

    return pd.DataFrame(data, columns=headers)

In [815]:
all_dfs = []

for index, row in tqdm.tqdm(day_before_tournament_start_df.iterrows()):
    
    start = row["season_start_date"]
    end = row["day_before_tourney_start"]
    year = row["year"]

    html = get_html_from_torvik_players(year, start, end, 40)
    tmp_df = get_data_from_html(html)
    tmp_df["Season"] = year

    all_dfs.append(tmp_df)

'Show 100 more' clicked (31/40)
'Show 100 more' clicked (32/40)
'Show 100 more' clicked (33/40)
'Show 100 more' clicked (34/40)
'Show 100 more' clicked (35/40)
'Show 100 more' clicked (36/40)
'Show 100 more' clicked (37/40)
'Show 100 more' clicked (38/40)
'Show 100 more' clicked (39/40)
'Show 100 more' clicked (40/40)

13it [45:33, 216.22s/it]

Loading URL: https://barttorvik.com/playerstat.php?link=y&sIndex=53&minmin=5&year=2021&start=20201101&end=20210317
Clicked on 'Games' column successfully.
'Show 100 more' clicked (1/40)
'Show 100 more' clicked (2/40)
'Show 100 more' clicked (3/40)
'Show 100 more' clicked (4/40)
'Show 100 more' clicked (5/40)
'Show 100 more' clicked (6/40)
'Show 100 more' clicked (7/40)
'Show 100 more' clicked (8/40)
'Show 100 more' clicked (9/40)
'Show 100 more' clicked (10/40)
'Show 100 more' clicked (11/40)
'Show 100 more' clicked (12/40)
'Show 100 more' clicked (13/40)
'Show 100 more' clicked (14/40)
'Show 100 more' clicked (15/40)
'Show 100 more' clicked (16/40)
'Show 100 more' clicked (17/40)
'Show 100 more' clicked (18/40)
'Show 100 more' clicked (19/40)
'Show 100 more' clicked (20/40)
'Show 100 more' clicked (21/40)
'Show 100 more' clicked (22/40)
'Show 100 more' clicked (23/40)
'Show 100 more' clicked (24/40)
'Show 100 more' clicked (25/40)
'Show 100 more' clicked (26/40)
'Show 100 more' clicked (27/40)
'Show 100 more' clicked (28/40)
'Show 100 more' clicked (29/40)
'Show 100 more' clicked (30/40)
'Show 100 more' clicked (31/40)
'Show 100 more' clicked (32/40)
'Show 100 more' clicked (33/40)
'Show 100 more' clicked (34/40)
'Show 100 more' clicked (35/40)
'Show 100 more' clicked (36/40)
'Show 100 more' clicked (37/40)
'Show 100 more' clicked (38/40)
'Show 100 more' clicked (39/40)
'Show 100 more' clicked (40/40)

14it [48:48, 209.84s/it]

Loading URL: https://barttorvik.com/playerstat.php?link=y&sIndex=53&minmin=5&year=2022&start=20211101&end=20220316
Clicked on 'Games' column successfully.
'Show 100 more' clicked (1/40)
'Show 100 more' clicked (2/40)
'Show 100 more' clicked (3/40)
'Show 100 more' clicked (4/40)
'Show 100 more' clicked (5/40)
'Show 100 more' clicked (6/40)
'Show 100 more' clicked (7/40)
'Show 100 more' clicked (8/40)
'Show 100 more' clicked (9/40)
'Show 100 more' clicked (10/40)
'Show 100 more' clicked (11/40)
'Show 100 more' clicked (12/40)
'Show 100 more' clicked (13/40)
'Show 100 more' clicked (14/40)
'Show 100 more' clicked (15/40)
'Show 100 more' clicked (16/40)
'Show 100 more' clicked (17/40)
'Show 100 more' clicked (18/40)
'Show 100 more' clicked (19/40)
'Show 100 more' clicked (20/40)
'Show 100 more' clicked (21/40)
'Show 100 more' clicked (22/40)
'Show 100 more' clicked (23/40)
'Show 100 more' clicked (24/40)
'Show 100 more' clicked (25/40)
'Show 100 more' clicked (26/40)
'Show 100 more' clicked (27/40)
'Show 100 more' clicked (28/40)
'Show 100 more' clicked (29/40)
'Show 100 more' clicked (30/40)
'Show 100 more' clicked (31/40)
'Show 100 more' clicked (32/40)
'Show 100 more' clicked (33/40)
'Show 100 more' clicked (34/40)
'Show 100 more' clicked (35/40)
'Show 100 more' clicked (36/40)
'Show 100 more' clicked (37/40)
'Show 100 more' clicked (38/40)
'Show 100 more' clicked (39/40)
'Show 100 more' clicked (40/40)

15it [52:13, 208.29s/it]

Loading URL: https://barttorvik.com/playerstat.php?link=y&sIndex=53&minmin=5&year=2023&start=20221101&end=20230315
Clicked on 'Games' column successfully.
'Show 100 more' clicked (1/40)
'Show 100 more' clicked (2/40)
'Show 100 more' clicked (3/40)
'Show 100 more' clicked (4/40)
'Show 100 more' clicked (5/40)
'Show 100 more' clicked (6/40)
'Show 100 more' clicked (7/40)
'Show 100 more' clicked (8/40)
'Show 100 more' clicked (9/40)
'Show 100 more' clicked (10/40)
'Show 100 more' clicked (11/40)
'Show 100 more' clicked (12/40)
'Show 100 more' clicked (13/40)
'Show 100 more' clicked (14/40)
'Show 100 more' clicked (15/40)
'Show 100 more' clicked (16/40)
'Show 100 more' clicked (17/40)
'Show 100 more' clicked (18/40)
'Show 100 more' clicked (19/40)
'Show 100 more' clicked (20/40)
'Show 100 more' clicked (21/40)
'Show 100 more' clicked (22/40)
'Show 100 more' clicked (23/40)
'Show 100 more' clicked (24/40)
'Show 100 more' clicked (25/40)
'Show 100 more' clicked (26/40)
'Show 100 more' clicked (27/40)
'Show 100 more' clicked (28/40)
'Show 100 more' clicked (29/40)
'Show 100 more' clicked (30/40)
'Show 100 more' clicked (31/40)
'Show 100 more' clicked (32/40)
'Show 100 more' clicked (33/40)
'Show 100 more' clicked (34/40)
'Show 100 more' clicked (35/40)
'Show 100 more' clicked (36/40)
'Show 100 more' clicked (37/40)
'Show 100 more' clicked (38/40)
'Show 100 more' clicked (39/40)
'Show 100 more' clicked (40/40)

16it [55:14, 200.14s/it]

Loading URL: https://barttorvik.com/playerstat.php?link=y&sIndex=53&minmin=5&year=2024&start=20231101&end=20240320
Clicked on 'Games' column successfully.
'Show 100 more' clicked (1/40)
'Show 100 more' clicked (2/40)
'Show 100 more' clicked (3/40)
'Show 100 more' clicked (4/40)
'Show 100 more' clicked (5/40)
'Show 100 more' clicked (6/40)
'Show 100 more' clicked (7/40)
'Show 100 more' clicked (8/40)
'Show 100 more' clicked (9/40)
'Show 100 more' clicked (10/40)
'Show 100 more' clicked (11/40)
'Show 100 more' clicked (12/40)
'Show 100 more' clicked (13/40)
'Show 100 more' clicked (14/40)
'Show 100 more' clicked (15/40)
'Show 100 more' clicked (16/40)
'Show 100 more' clicked (17/40)
'Show 100 more' clicked (18/40)
'Show 100 more' clicked (19/40)
'Show 100 more' clicked (20/40)
'Show 100 more' clicked (21/40)
'Show 100 more' clicked (22/40)
'Show 100 more' clicked (23/40)
'Show 100 more' clicked (24/40)
'Show 100 more' clicked (25/40)
'Show 100 more' clicked (26/40)
'Show 100 more' clicked (27/40)
'Show 100 more' clicked (28/40)
'Show 100 more' clicked (29/40)
'Show 100 more' clicked (30/40)
'Show 100 more' clicked (31/40)
'Show 100 more' clicked (32/40)
'Show 100 more' clicked (33/40)
'Show 100 more' clicked (34/40)
'Show 100 more' clicked (35/40)
'Show 100 more' clicked (36/40)
'Show 100 more' clicked (37/40)
'Show 100 more' clicked (38/40)
'Show 100 more' clicked (39/40)
'Show 100 more' clicked (40/40)

17it [58:12, 205.47s/it]

In [816]:
final_df = pd.concat(all_dfs, axis=0)

In [817]:
final_df = final_df[final_df["Min%"].notnull()]

In [818]:
final_df.to_csv("torvik_player_data2.csv")

### Scrape ESPN

In [ ]:
# def get_game_ids(date: str):
#     url = f"https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/scoreboard?dates={date}"
#     headers = {"User-Agent": "Mozilla/5.0"}
    
#     response = requests.get(url, headers=headers)
    
#     if response.status_code == 200:
#         data = response.json()
#         return [game.get("id") for game in data.get("events", [])]
#     else:
#         print(f"Failed to fetch data: {response.status_code}")
#         return []


# def get_box_score(game_id):

#     url = f'https://site.api.espn.com/apis/site/v2/sports/basketball/mens-college-basketball/summary?event={game_id}'

#     response = requests.get(url)

#     data = json.loads(response.text)

#     columns = ['team', 'player_name'] + data['boxscore']['players'][0]['statistics'][0]["names"]
#     team1 = data['boxscore']['players'][0]['statistics'][0]["athletes"]
#     team1_name = data['boxscore']['players'][0]['team']['location']
#     team2 = data['boxscore']['players'][1]['statistics'][0]["athletes"]
#     team2_name = data['boxscore']['players'][1]['team']['location']

#     all_data = []

#     for player in team1:

#         if len(player['stats']) > 0:
#             name = player["athlete"]["displayName"]
#             stats = player['stats']
#             all_data.append([team1_name, name] + stats)

#     for player in team2:

#         if len(player['stats']) > 0:
#             name = player["athlete"]["displayName"]
#             stats = player['stats']
#             all_data.append([team2_name, name] + stats)

#     return pd.DataFrame(all_data,columns=columns)


# bs = []

# for date in tqdm.tqdm(all_first_round_dates):
#     game_ids = get_game_ids(date)
#     for game in game_ids:
#         b = get_box_score(game)
#         b["Season"] = date[0:4]
#         bs.append(b)
    
# ncaam_box_scores = pd.concat(bs, axis = 0)

In [954]:
def get_game_ids(date: str) -> List[str]:
    """
    Retrieve game IDs for men's college basketball games on a given date.

    Args:
        date (str): Date in the format YYYYMMDD.

    Returns:
        List[str]: A list of game IDs retrieved from the ESPN API.
    """
    url = (f"https://site.api.espn.com/apis/site/v2/sports/basketball/"
           f"mens-college-basketball/scoreboard?dates={date}")
    headers = {"User-Agent": "Mozilla/5.0"}
    
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        data = response.json()
        return [game.get("id") for game in data.get("events", [])]
    else:
        print(f"Failed to fetch game IDs for date {date}: {response.status_code}")
        return []

def extract_team_box_scores(team_data: dict) -> List[List[Any]]:
    """
    Extract box score data for a single team from the ESPN API box score data.

    Args:
        team_data (dict): Dictionary containing team box score information.

    Returns:
        List[List[Any]]: List of player box score data rows for the team.
    """
    team_name = team_data['team']['location']
    # Assumes the first statistics block contains the relevant info
    stats_block = team_data['statistics'][0]
    players = stats_block.get("athletes", [])
    rows = []
    
    for player in players:
        # Only include players with non-empty stats
        if player.get('stats'):
            player_name = player["athlete"]["displayName"]
            stats = player['stats']
            row = [team_name, player_name] + stats
            rows.append(row)
    return rows

def get_box_score(game_id: Union[str, int]) -> pd.DataFrame:
    """
    Retrieve and process the box score data for a specific game.

    Args:
        game_id (Union[str, int]): The game identifier.

    Returns:
        pd.DataFrame: DataFrame containing box score data for both teams.
                    Returns an empty DataFrame if data retrieval fails.
    """
    url = (f"https://site.api.espn.com/apis/site/v2/sports/basketball/"
           f"mens-college-basketball/summary?event={game_id}")
    response = requests.get(url)
    
    if response.status_code != 200:
        print(f"Failed to fetch box score for game ID {game_id}: {response.status_code}")
        return pd.DataFrame()  # Return empty DataFrame on error

    data = response.json()
    
    # Retrieve the list of team boxscore data; expect two teams
    players_data = data.get('boxscore', {}).get('players', [])
    if len(players_data) < 2:
        print(f"Incomplete box score data for game ID {game_id}")
        return pd.DataFrame()
        
    # Define columns using team/player info plus statistic names from the first team's block
    statistic_names = players_data[0]['statistics'][0].get("names", [])
    columns = ['team', 'player_name'] + statistic_names
    
    # Process box score data for both teams
    team1_rows = extract_team_box_scores(players_data[0])
    team2_rows = extract_team_box_scores(players_data[1])
    all_rows = team1_rows + team2_rows
    
    return pd.DataFrame(all_rows, columns=columns)

def aggregate_box_scores(dates: List[str]) -> pd.DataFrame:
    """
    Aggregate box score data for a list of dates.

    Args:
        dates (List[str]): List of dates in the format YYYYMMDD.

    Returns:
        pd.DataFrame: Combined DataFrame containing box score data for all games on the given dates.
    """
    all_box_scores = []
    
    for date in tqdm.tqdm(dates, desc="Processing dates"):
        game_ids = get_game_ids(date)
        for game_id in game_ids:
            box_score_df = get_box_score(game_id)
            if not box_score_df.empty:
                # Add season column (using the first 4 characters of the date, i.e., the year)
                box_score_df["Season"] = date[:4]
                all_box_scores.append(box_score_df)
    
    if all_box_scores:
        return pd.concat(all_box_scores, ignore_index=True)
    else:
        return pd.DataFrame()

In [955]:
ncaam_box_scores2 = aggregate_box_scores(all_first_round_dates)

Processing dates: 100%|██████████| 34/34 [04:54<00:00,  8.67s/it]

In [957]:
ncaam_box_scores = ncaam_box_scores2.copy()

In [ ]:
final_df[
    (final_df.team.str.contains("So"))
    & (final_df.Season == "2013")]

,team,player_name,MIN,FG,3PT,FT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,Season
2868,Southern,Javan Mitchell,38,3-4,0-0,1-2,0,4,4,2,0,3,2,3,7,2013
2869,Southern,Brandon Moore,29,2-2,1-1,2-2,0,3,3,0,0,4,0,3,7,2013
2870,Southern,Cameron Monroe,4,0-1,0-0,0-0,0,0,0,0,0,0,1,0,0,2013
2871,Southern,Derick Beltran,39,6-14,4-8,5-7,0,3,3,3,1,0,1,1,21,2013
2872,Southern,Jameel Grace,26,1-8,0-2,2-2,1,6,7,3,2,0,2,0,4,2013
2873,Southern,Madut Bol,9,1-1,1-1,0-0,0,0,0,1,0,0,1,2,3,2013
2874,Southern,Christopher Hyder,14,0-1,0-0,0-0,0,0,0,0,1,0,1,1,0,2013
2875,Southern,Malcolm Miller,24,3-12,3-10,0-2,0,2,2,0,0,1,1,1,9,2013
2876,Southern,YonDarius Johnson,17,2-3,1-1,2-3,0,1,1,1,0,0,1,1,7,2013
2935,South Dakota St.,Jordan Dykstra,40,5-11,1-3,1-2,1,8,9,1,0,0,1,4,12,2013
2936,South Dakota St.,Tony Fiegen,40,6-6,0-0,0-0,1,1,2,1,1,0,4,2,12,2013
2937,South Dakota St.,Chad White,32,1-8,0-5,0-0,0,1,1,1,0,0,2,4,2,2013
2938,South Dakota St.,Brayden Carlson,40,8-12,3-6,1-2,2,6,8,4,1,0,2,0,20,2013
2939,South Dakota St.,Nate Wolters,40,3-14,0-5,4-4,1,4,5,6,1,0,3,0,10,2013
2940,South Dakota St.,Jake Bittle,8,0-1,0-0,0-0,0,1,1,0,0,0,0,0,0,2013

In [958]:

ncaam_box_scores["team"] = ncaam_box_scores["team"].str.replace(r'\bState\b', 'St.', regex=True)

# Optionally, save the aggregated box scores to a CSV file
ncaam_box_scores.to_csv("ncaam_box_scores.csv", index=False)

In [956]:
ncaam_box_scores2[(ncaam_box_scores2.team == "Gonzaga")
                 & (ncaam_box_scores2.Season == "2021")].head(15)

,team,player_name,MIN,FG,3PT,FT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,Season
7642,Gonzaga,Drew Timme,22,3-7,0-0,4-4,3,3,6,5,0,1,0,2,10,2021
7643,Gonzaga,Corey Kispert,27,8-12,6-9,1-1,1,4,5,2,0,0,1,0,23,2021
7644,Gonzaga,Jalen Suggs,18,2-8,0-3,2-2,0,4,4,2,1,1,4,3,6,2021
7645,Gonzaga,Andrew Nembhard,27,1-5,0-4,2-2,1,3,4,5,2,0,1,1,4,2021
7646,Gonzaga,Joel Ayayi,28,6-12,1-3,2-2,1,8,9,2,1,0,1,0,15,2021
7647,Gonzaga,Ben Gregg,5,0-1,0-0,0-1,0,2,2,0,0,0,0,2,0,2021
7648,Gonzaga,Anton Watson,24,7-7,1-1,2-2,3,4,7,4,3,0,0,1,17,2021
7649,Gonzaga,Oumar Ballo,6,1-1,0-0,0-0,0,2,2,0,0,1,1,0,2,2021
7650,Gonzaga,Pavel Zakharov,1,0-0,0-0,0-0,0,0,0,0,0,0,0,0,0,2021
7651,Gonzaga,Will Graves,1,0-0,0-0,0-0,0,0,0,0,0,0,0,0,0,2021
7652,Gonzaga,Dominick Harris,7,1-1,1-1,2-2,0,0,0,0,0,0,0,2,5,2021
7653,Gonzaga,Julian Strawther,9,3-4,3-4,0-0,0,2,2,0,0,0,0,2,9,2021
7654,Gonzaga,Martynas Arlauskas,2,0-0,0-0,1-2,0,0,0,0,0,0,0,0,1,2021
7655,Gonzaga,Matthew Lang,2,0-0,0-0,0-0,0,0,0,0,0,0,0,0,0,2021
7656,Gonzaga,Aaron Cook,21,2-3,2-2,0-0,0,1,1,7,1,0,3,2,6,2021

In [959]:
tmp_box = ncaam_box_scores[(ncaam_box_scores.Season == "2024") & 
                 (ncaam_box_scores.team == "Kansas")]

In [960]:
tmp = final_df[(final_df.Team == "Kansas")
         & (final_df.Season == 2024)].copy()

### Match Torvik and Box Score Team Names

In [ ]:
box_score_teams = ncaam_box_scores.team.unique().tolist()

In [ ]:
torvik_teams = final_df.Team.unique().tolist()

In [ ]:
def match_lists(list1, list2):
    matched = [item if item in list2 else "" for item in list1]
    return pd.DataFrame({'Box_Score_Team': list1, 'Torvik_Team': matched})

In [ ]:
team_lookup = match_lists(box_score_teams, torvik_teams)

In [983]:
team_lookup

         Box_Score_Team         Torvik_Team
0          Morehead St.        Morehead St.
1            Louisville          Louisville
2    East Tennessee St.  East Tennessee St.
3            Pittsburgh          Pittsburgh
4         Robert Morris       Robert Morris
..                  ...                 ...
228      Long Beach St.      Long Beach St.
229             Samford             Samford
230             McNeese         McNeese St.
231            Duquesne            Duquesne
232      Washington St.      Washington St.

[233 rows x 2 columns]

In [981]:
final_df[final_df.Team.str.lower().str.contains("northwestern")].Team.unique()

array(['Northwestern', 'Northwestern St.'], dtype=object)

In [986]:
insert = pd.DataFrame( 
[("Detroit Mercy", "Detroit Mercy"),
("South Florida", "South Florida"),
('Loyola Maryland', "Loyola MD"),
('Southern Miss', "Southern Miss"),
('Pacific', "Pacific"),
('Northwestern St.', "Northwestern St."),
], columns = ["Box_Score_Team",	"Torvik_Team"]
)

In [987]:
team_lookup = pd.concat([team_lookup, insert], axis = 0)

In [ ]:
# final_df = final_df.drop("Box_Score_Team", axis=1)

In [969]:
tmp = ncaam_box_scores.merge(team_lookup, how="left", left_on="team", right_on="Box_Score_Team")

In [ ]:
def update_mapping(mapping_df, col1_name, col2_name, col1_value, col2_value):
    mapping_df.loc[mapping_df[col1_name] == col1_value, col2_name] = col2_value
    return mapping_df

In [ ]:
team_lookup = update_mapping(team_lookup, "Box_Score_Team", "Torvik_Team","Grambling", "Grambling St.")

In [989]:
# Write this to a csv so we can reuse the mapping 
team_lookup.to_csv("../data/sky_data/mappings/espn_to_torvik.csv")

In [820]:
final_df["Torvik_Team"] = final_df["Team"].copy()

In [991]:
final_df = final_df.merge(team_lookup, on="Torvik_Team", how="left")

In [992]:
final_df["Games"] = final_df["Games"].astype(int)

### Find Missing Players

In [998]:
team_seasons = ncaam_box_scores[["team", "Season"]].drop_duplicates()
team_seasons = list(team_seasons.itertuples(index=False, name=None))

In [999]:
def get_first_initial_and_last(name: str) -> tuple[str, str]:
    """
    Remove common suffixes from the player's name and return the first initial and last name.

    Parameters:
        name (str): The player's full name.

    Returns:
        tuple: A tuple (first_initial, last_name) after cleaning the name.
    """
    parts = name.split()
    # Define common suffixes to remove (case-insensitive)
    suffixes = {"jr", "jr.", "sr", "sr.", "i", "ii", "iii", "iv"}
    
    # Remove any trailing suffixes
    while parts and parts[-1].lower() in suffixes:
        parts.pop()
    
    # If no parts remain, return empty strings
    if not parts:
        return ("", "")
    
    first_initial = parts[0][0].upper() if parts[0] else ""
    # Capitalize the last name for consistency
    last_name = parts[-1].capitalize() if parts[-1] else ""
    return (first_initial, last_name)

def has_initial_last_match(name: str, names_list: list[str]) -> bool:
    """
    Check if a given player's name (after cleaning) has a matching first initial and last name
    in a list of names.

    Parameters:
        name (str): The player's full name to check.
        names_list (list[str]): A list of player names to compare against.

    Returns:
        bool: True if a matching name (by first initial and last name) is found; False otherwise.
    """
    target_initial, target_last = get_first_initial_and_last(name)
    
    for other in names_list:
        other_initial, other_last = get_first_initial_and_last(other)
        if target_initial == other_initial and target_last == other_last:
            return True
    return False

def find_players_with_high_distance(list1: list[str], list2: list[str], min_threshold: int = 3) -> list[str]:
    """
    Identify players from list1 that are considered missing compared to list2 based on Levenshtein 
    distance and cleaned name matching. For each name in list1, the function finds the closest match 
    in list2 using Levenshtein distance. If the distance is above the threshold and no similar name 
    (by first initial and last name) is found in list2, then the player is flagged as missing.

    Parameters:
        list1 (list[str]): List of player names to check.
        list2 (list[str]): List of player names to compare against.
        min_threshold (int): Minimum Levenshtein distance to consider a name as missing.

    Returns:
        list[str]: List of names from list1 that are considered missing.
    """
    missing_players = []
    
    for name1 in list1:
        # Find the best match in list2 based on Levenshtein distance
        min_dist, best_match = min(
            ((Levenshtein.distance(name1, name2), name2) for name2 in list2),
            key=lambda x: x[0]
        )
        
        # If the distance is high enough, check for a first initial + last name match
        if min_dist >= min_threshold:
            if not has_initial_last_match(name1, list2):
                missing_players.append(name1)
    
    return missing_players

In [1000]:
import pandas as pd

def add_team_season_games_played_columns(df: pd.DataFrame, team_col:str, season_col:str) -> pd.DataFrame:
    """
    Adds columns to the dataframe for total number of games played by each team/season
    and the percentage of total games played by each player.

    Args:
        df (pd.DataFrame): Input dataframe with columns 'team', 'season', 'player', 
                           'PRPG', and 'Games'.

    Returns:
        pd.DataFrame: DataFrame with added columns for total games played per team/season
                      and percentage of games played by each player.
    """
    # Ensure the dataframe is sorted by team and season, if not already
    df = df.sort_values(by=[team_col, season_col])
    
    # Calculate the total number of games played for each team/season using a groupby and transform
    df['total_team_season_games'] = df.groupby([team_col, season_col])['Games'].transform('max')
    
    # Calculate the percentage of total games played by each player
    df['games_played_pct'] = df['Games'] / df['total_team_season_games']
    
    return df

In [1001]:
# injured_players = []
# injured_players_value = []

# for team, season in team_seasons:
    
#     torvik_data = final_df[(final_df["Box_Score_Team"] == team)
#                            & (final_df["Season"] == int(season))
#                            ].copy()
    
#     torvik_data["Min%"] = torvik_data["Min%"].astype(float)
#     torvik_data["PRPG!"] = torvik_data["PRPG!"].astype(float)
#     torvik_data["total_value"] = torvik_data["Min%"] * torvik_data["PRPG!"]
#     torvik_data["total_value_perc"] = torvik_data["total_value"] / torvik_data["total_value"].sum() 
    
#     bs_data = ncaam_box_scores[(ncaam_box_scores["team"] == team)
#                            & (ncaam_box_scores["Season"] == season)]
    
#     torvik_players = torvik_data["Player"].unique().tolist()

#     bs_players = bs_data["player_name"].unique().tolist()

#     high_distance_players = find_players_with_high_distance(torvik_players, bs_players, min_threshold=6)

#     team_missing_player_value = 0

#     for player in high_distance_players:
#         player_value = torvik_data[torvik_data.Player == player].total_value_perc.iloc[0]
#         team_missing_player_value += player_value

#     injured_players.append(high_distance_players)
#     injured_players_value.append(team_missing_player_value)

In [1002]:
final_df = add_team_season_games_played_columns(final_df, 'Box_Score_Team', 'Season')

In [1003]:
# ---- REVISED ----

injured_players = []
injured_players_value = []
health_scores = []

for team, season in team_seasons:
    
    torvik_data = final_df[(final_df["Box_Score_Team"] == team)
                           & (final_df["Season"] == season)
                           ].copy()
             
    torvik_data["Min%"] = torvik_data["Min%"].astype(float)
    torvik_data["PRPG!"] = torvik_data["PRPG!"].astype(float)
    torvik_data["total_value"] = torvik_data["Min%"] * torvik_data["PRPG!"]
    torvik_data["total_value_perc"] = torvik_data["total_value"] / torvik_data["total_value"].sum() 
    
    bs_data = ncaam_box_scores[(ncaam_box_scores["team"] == team)
                           & (ncaam_box_scores["Season"] == season)]
    
    torvik_players = torvik_data["Player"].unique().tolist()

    bs_players = bs_data["player_name"].unique().tolist()

    high_distance_players = find_players_with_high_distance(torvik_players, bs_players, min_threshold=6)

    torvik_data['player_availability'] = torvik_data['Player'].apply(lambda x: 0 if x in high_distance_players else 1)

    health_score = (torvik_data['player_availability'] * torvik_data["PRPG!"]).sum() / (torvik_data['games_played_pct'] * torvik_data["PRPG!"]).sum()

    health_scores.append(health_score)

    team_missing_player_value = 0

    for player in high_distance_players:
        player_value = torvik_data[torvik_data.Player == player].total_value_perc.iloc[0]
        team_missing_player_value += player_value

    injured_players.append(high_distance_players)
    injured_players_value.append(team_missing_player_value)

In [ ]:
# df['Player_Status'] = df['Player'].isin(high_distance_players).astype(int)

In [1004]:
team_seasons = pd.DataFrame(team_seasons, columns=["team", "Season"])

In [1005]:
team_seasons["injured_players"] = injured_players

In [1006]:
team_seasons["injured_players_value"] = injured_players_value

In [1007]:
team_seasons["health_score"] = health_scores

In [1008]:
team_seasons["n_injured_players"] = team_seasons["injured_players"].apply(lambda x: len(x))

In [1009]:
team_seasons.sort_values(by="health_score", ascending=False)

,team,Season,injured_players,injured_players_value,health_score,n_injured_players
598,Texas Southern,2018,"[Kevin Scott, Jerry Perry, Kevin Granger Jr., ...",-0.014147,1.270000,4
932,Saint Peter's,2024,[Elijah Perkins],-0.019554,1.261918,1
76,New Mexico St.,2010,"[Kelly Merker, Robert Lumpkins, Bandja Sy]",-0.013431,1.240464,3
133,Duke,2011,[],0.000000,1.203151,0
575,Arizona,2017,[],0.000000,1.171562,0
...,...,...,...,...,...,...
73,Purdue,2010,"[Robbie Hummel, Mark Wohlford]",0.298699,0.717431,2
592,Kansas St.,2018,"[Dean Wade, James Love III]",0.354018,0.715739,2
455,California,2016,"[Tyrone Wallace, Jabari Bird]",0.355744,0.664387,2
744,Texas Southern,2021,"[Galen Alexander, Joirdon Karl Nichols]",0.337422,0.651445,2
562,Mount St. Mary's,2017,"[Elijah Long, Ryan Gomes]",0.331524,0.627803,2

In [1010]:
team_seasons[(team_seasons.Season == "2024")].sort_values(by="injured_players_value", ascending=False).head(10)

,team,Season,injured_players,injured_players_value,health_score,n_injured_players
941,Kansas,2024,[Kevin McCullar Jr.],0.226070,0.816101,1
920,Northwestern,2024,"[Matthew Nicholson, Ty Berry]",0.180250,0.814789,2
896,Grambling,2024,"[Terrence Lewis, Quintin Murrell]",0.100877,0.864357,2
903,Baylor,2024,"[Dantwan Grimes, Langston Love]",0.088463,0.888889,2
915,Saint Mary's,2024,[Joshua Jefferson],0.087730,0.922570,1
919,Florida,2024,[Micah Handlogten],0.070952,0.926730,1
946,Oregon,2024,"[Nate Bittle, Keeshawn Barthelemy, Jesse Zarzu...",0.070798,1.045439,3
907,Duke,2024,[Caleb Foster],0.060600,0.985689,1
950,Nevada,2024,"[Hunter McIntosh, Jazz Gardner]",0.059215,0.932646,2
926,Wagner,2024,"[Zaire Williams, Rahmir Moore, Di'Andre Howell...",0.048260,0.967742,4

In [1011]:
team_seasons[(team_seasons.Season == "2019")].sort_values(by="health_score", ascending=True).head(20)

,team,Season,injured_players,injured_players_value,health_score,n_injured_players
690,Abilene Christian,2019,"[B.J. Maxwell, Jalone Friday]",0.256854,0.724035,2
647,Kansas St.,2019,[Dean Wade],0.241457,0.786827,1
691,Kentucky,2019,"[PJ Washington, Quade Green]",0.234652,0.799739,2
698,Montana,2019,[Jamar Akoh],0.125274,0.872357,1
685,Kansas,2019,"[Lagerald Vick, Udoka Azubuike]",0.179027,0.892164,2
663,Mississippi St.,2019,[Nick Weatherspoon],0.083316,0.915009,1
692,Fairleigh Dickinson,2019,[Xzavier Malone-Key],0.069116,0.917274,1
701,Syracuse,2019,"[Frank Howard, Bourama Sidibe]",0.087270,0.921788,2
672,Minnesota,2019,"[Matz Stockman, Eric Curry, Isaiah Washington]",0.024882,0.938953,3
688,Florida,2019,"[Keith Stone, Deaundrae Ballard, Mike Okauru]",0.036181,0.940439,3
703,Purdue,2019,[Evan Boudreaux],0.027556,0.947129,1
654,Oregon,2019,"[Bol Bol, Abu Kigab]",0.101650,0.950526,2
681,Michigan St.,2019,"[Kyle Ahrens, Joshua Langford]",0.081765,0.954653,2
682,Belmont,2019,"[Caleb Hollander, Derek Sabin]",0.028420,0.957337,2
680,Bradley,2019,[],0.000000,0.957338,0
670,Saint Louis,2019,[Carte'Are Gordon],0.022467,0.962976,1
695,Villanova,2019,"[Cole Swider, Jahvon Quinerly]",0.008770,0.980119,2
668,Ohio St.,2019,"[Justin Ahrens, Jaedon LeDee]",0.020918,0.987424,2
662,Liberty,2019,[Keegan McDowell],0.004599,0.987965,1
656,Washington,2019,[],0.000000,0.989207,0

In [1012]:
team_seasons.sort_values(by="injured_players_value", ascending=False).iloc[0]["injured_players"]

['Tyrone Wallace', 'Jabari Bird']

In [1013]:
ncaam_box_scores[(ncaam_box_scores.team == "Michigan")
                 & (ncaam_box_scores.Season == "2022")]

,team,player_name,MIN,FG,3PT,FT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,Season
8034,Michigan,Caleb Houstan,36,5-11,3-8,0-0,1,4,5,2,0,0,1,0,13,2022
8035,Michigan,Moussa Diabate,27,2-4,0-0,3-4,2,7,9,2,0,0,2,4,7,2022
8036,Michigan,Hunter Dickinson,35,8-10,0-1,5-5,1,5,6,1,1,4,4,1,21,2022
8037,Michigan,Frankie Collins,31,6-7,1-2,1-1,0,6,6,2,1,0,1,4,14,2022
8038,Michigan,Eli Brooks,40,5-13,0-1,6-8,1,6,7,6,2,0,3,1,16,2022
8039,Michigan,Terrance Williams II,9,0-1,0-1,2-2,0,1,1,1,0,0,1,0,2,2022
8040,Michigan,Brandon Johns Jr.,13,0-0,0-0,0-0,0,1,1,1,1,0,1,1,0,2022
8041,Michigan,Kobe Bufkin,9,0-2,0-1,2-2,0,0,0,0,0,0,2,0,2,2022

In [1014]:
final_df[(final_df.Team == "Michigan")
         & (final_df.Season == "2022")]

,Rk,Class,Height,Player,Team,Conf,Games,Min%,PRPG!,BPM,...,AST,TO,BLK,STL,FTR,Season,Torvik_Team,total_team_season_games,games_played_pct,Box_Score_Team
19823,26,So,7-1,Hunter Dickinson,Michigan,B10,29,74.9,5.6,9.2,...,15.8,14.2,4.7,0.8,25.1,2022,Michigan,31.0,0.935484,Michigan
19824,266,Sr,6-1,Eli Brooks,Michigan,B10,31,89.2,3.9,5.0,...,14.2,12.9,0.3,1.9,22.2,2022,Michigan,31.0,1.000000,Michigan
19825,284,Sr,6-1,DeVante' Jones,Michigan,B10,31,73.2,3.6,4.9,...,29.2,19.5,0.3,2.0,29.3,2022,Michigan,31.0,1.000000,Michigan
19826,744,Fr,6-8,Caleb Houstan,Michigan,B10,31,80.0,2.3,2.5,...,7.7,16.5,0.8,1.4,31.6,2022,Michigan,31.0,1.000000,Michigan
19827,999,Fr,6-11,Moussa Diabate,Michigan,B10,29,58.1,2.5,1.6,...,6.0,17.5,3.3,0.9,37.4,2022,Michigan,31.0,0.935484,Michigan
19828,1014,So,6-7,Terrance Williams II,Michigan,B10,28,34.0,1.4,1.5,...,5.8,12.4,0.2,0.6,27.0,2022,Michigan,31.0,0.903226,Michigan
19829,1580,Fr,6-4,Kobe Bufkin,Michigan,B10,27,23.4,0.4,-0.0,...,4.8,15.9,1.1,2.2,26.0,2022,Michigan,31.0,0.870968,Michigan
19830,1743,So,6-7,Jace Howard,Michigan,B10,14,5.2,0.2,-0.4,...,7.9,22.5,3.2,1.8,28.6,2022,Michigan,31.0,0.451613,Michigan
19831,1751,Sr,6-8,Brandon Johns Jr.,Michigan,B10,28,30.2,0.3,-0.4,...,4.1,19.5,1.9,0.8,28.6,2022,Michigan,31.0,0.903226,Michigan
19832,2258,Fr,6-1,Frankie Collins,Michigan,B10,28,21.7,0.1,-1.7,...,25.1,29.8,0.8,2.4,45.6,2022,Michigan,31.0,0.903226,Michigan

### Match ESPN and Kaggle Team Names

In [1077]:
kaggle_team_names = pd.read_csv("../data/MTeams.csv")

In [1078]:
all_kaggle_teams = kaggle_team_names.TeamName.unique().tolist()

In [1079]:
injury_data = team_seasons.copy()

In [1080]:
injury_data["team"] = injury_data["team"].str.replace(r'St\.(?!\w)', 'St', regex=True)

In [1081]:
injury_data_teams = injury_data["team"].unique().tolist()

In [1082]:
def match_lists(list1, list2):
    matched = [item if item in list2 else "" for item in list1]
    return pd.DataFrame({'Injury_Data_Team': list1, 'Kaggle_Team': matched})

In [1083]:
team_lookup2 = match_lists(injury_data_teams, all_kaggle_teams)

In [1084]:
missing = team_lookup2[team_lookup2.Kaggle_Team == ""].copy()

In [1085]:
chatgpt_matches = pd.DataFrame([
    ('East Tennessee St', 'ETSU'),
    ('Stephen F. Austin', 'SF Austin'),
    ('North Dakota St', 'N Dakota St'),
    ('Cal St Northridge', 'CS Northridge'),
    ('UConn', 'Connecticut'),
    ('American University', 'American Univ'),
    ('Western Kentucky', 'WKU'),
    ('Arkansas-Pine Bluff', 'Ark Pine Bluff'),
    ('Sam Houston', 'Sam Houston St'),
    ("Saint Mary's", "St Mary's CA"),
    ('UTSA', 'UT San Antonio'),
    ('Boston University', 'Boston Univ'),
    ('Long Island University', 'LIU Brooklyn'),
    ("Saint Peter's", 'St Peter\'s'),
    ('Northern Colorado', 'N Colorado'),
    ('Southern', 'Southern Univ'),
    ('North Carolina A&T', 'NC A&T'),
    ('South Dakota St', 'S Dakota St'),
    ('Saint Louis', 'St Louis'),
    ('Eastern Kentucky', 'E Kentucky'),
    ('George Washington', 'G Washington'),
    ('Coastal Carolina', 'Coastal Car'),
    ('North Carolina Central', 'NC Central'),
    ('Western Michigan', 'W Michigan'),
    ('UAlbany', 'SUNY Albany'),
    ("Saint Joseph's", 'St Joseph\'s PA'),
    ('NC St', 'NC State'),
    ('Milwaukee', 'WI Milwaukee'),
    ('Texas Southern', 'TX Southern'),
    ('Ole Miss', 'Mississippi'),
    ('Eastern Washington', 'E Washington'),
    ("Hawai'i", 'Hawaii'),
    ('Middle Tennessee', 'MTSU'),
    ('Cal St Bakersfield', 'CS Bakersfield'),
    ('Green Bay', 'WI Green Bay'),
    ('Little Rock', 'Ark Little Rock'),
    ('Miami', 'Miami FL'),
    ('Florida Gulf Coast', 'FGCU'),
    ('Northern Kentucky', 'N Kentucky'),
    ('Kent St', 'Kent'),
    ("Mount St Mary's", 'Mt St Mary\'s'),
    ('Cal St Fullerton', 'CS Fullerton'),
    ('Charleston', 'Col Charleston'),
    ('Pennsylvania', 'Penn'),
    ('Loyola Chicago', 'Loyola-Chicago'),
    ('Gardner-Webb', 'Gardner Webb'),
    ('Abilene Christian', 'Abilene Chr'),
    ('Fairleigh Dickinson', 'F Dickinson'),
    ('App St', 'Appalachian St'),
    ('Kennesaw St', 'Kennesaw'),
    ('Florida Atlantic', 'FL Atlantic'),
    ('Texas A&M-Corpus Christi', 'TAM C. Christi'),
    ('McNeese', 'McNeese St'),
    ('Detroit Mercy', 'Detroit'),
    ('Loyola Maryland', 'Loyola MD'),
    ('Northwestern St', 'Northwestern LA'),

], columns = ["Injury_Data_Team", "Kaggle_Team"]
)

In [1086]:
team_lookup2 = team_lookup2.merge(chatgpt_matches, how="left", on="Injury_Data_Team")

In [1087]:
import numpy as np
team_lookup2["TeamName"] = np.where(team_lookup2.Kaggle_Team_x == "", team_lookup2.Kaggle_Team_y, team_lookup2.Kaggle_Team_x)

In [1088]:
injury_data["Injury_Data_Team"] = injury_data["team"].copy()

In [1089]:
injury_data = injury_data.merge(team_lookup2[["Injury_Data_Team", "TeamName"]], how="left", on="Injury_Data_Team")

In [1090]:
injury_data_final = injury_data[["TeamName", "Season", "injured_players", "injured_players_value", 
                                 "health_score", "n_injured_players"]].copy()

In [1091]:
injury_data_final = injury_data_final.merge(kaggle_team_names[["TeamID", "TeamName"]], 
                        how="left", on="TeamName")

In [1092]:
injury_data_final[injury_data_final.TeamName.str.contains("South")]

,TeamName,Season,injured_players,injured_players_value,health_score,n_injured_players,TeamID
220,South Florida,2012,[LaVonte Dority],0.004271,1.081678,1,1378
250,Southern Miss,2012,[],0.000000,1.062778,0,1379
288,Southern Univ,2013,[Aaron Alston],-0.011837,1.084553,1,1380
422,TX Southern,2015,"[Christian McCoggle, Giovanni Mack, Nevin John...",-0.011496,1.099220,4,1411
524,TX Southern,2017,"[Derrick Griffin, Jamie Rutherford]",0.219117,0.871250,2,1411
539,South Carolina,2017,"[Ran Tut, Khadim Gueye, Jarrell Holliman]",-0.023085,1.157634,3,1376
598,TX Southern,2018,"[Kevin Scott, Jerry Perry, Kevin Granger Jr., ...",-0.014147,1.270000,4,1411
744,TX Southern,2021,"[Galen Alexander, Joirdon Karl Nichols]",0.337422,0.651445,2,1411
828,TX Southern,2022,[Davon Barnes],0.000000,1.040460,1,1411
947,South Carolina,2024,"[Stephen Clark, Morris Ugusuk]",0.003233,1.080531,2,1376

In [1093]:
injury_data_final.to_csv("../data/sky_data/injury_data.csv")

In [1096]:
injury_data_final[injury_data_final.TeamName == "Southern Univ"]

,TeamName,Season,injured_players,injured_players_value,health_score,n_injured_players,TeamID
288,Southern Univ,2013,[Aaron Alston],-0.011837,1.084553,1,1380